version: '3.8'
services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=practice_db
    ports:
      - 3309:3307
    volumes:
      - "db:/var/lib/mysql"
      - "/var/run/mysql/mysql.sock:/var/run/mysql/mysql.sock"
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: pma
    links:
      - mysqldb
    environment:
      - PMA_HOST=127.0.0.1
      - PMA_PORT=3308
      - PMA_USER=root
      - PMA_PASSWORD=123456
      - PMA_ARBITRARY=1
    ports:
      - 3308:80
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
  practice-api:
    depends_on:
      - mysqldb
    build: ./practice-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 6868:8080
    environment:
      - DB_HOST=127.0.0.1
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=practice_db
      - DB_PORT=3307
      - CLIENT_ORIGIN=http://127.0.0.1:8888
    networks:
      - backend
      - frontend
  practice-ui:
    depends_on:
      - practice-api
    build:
      context: ./practice-ui
      args:
        - REACT_APP_API_BASE_URL=http://127.0.0.1:6868/api
    ports:
      - 8888:80
    networks:
      - frontend
volumes: 
  db:
networks:
  backend:
  frontend: